#!/bin/sh

set $exit_code=0

regex="(aos\.y.*\.d.*(?<!data)(?<!template)$)|(aos.instrument)"

echo "=== Running clojure tests"
clojure -R:test:unstrumented-clj \
        -e "(require,'patch.clj-2443)" \
        -m cognitect.test-runner -d src -r "$regex"

if [ $? -eq 1 ]; then
    exit_code=1
fi

echo "\n=== Running cljs tests"
clojure -R:test:unstrumented-cljs \
        -m cljs-test-runner.main -c cljs-opts.edn -d src -r "$regex"

if [ $? -eq 1 ]; then
    exit_code=1
fi

exit $exit_code
