#!/bin/bash

exit_code=0
ns_flag="-n"
ns="aoc.instrument"

if [ $2 ] && [ $3 ]; then
    printf -v user_ns "aoc.y$1.d%02d.$3" "$2"
else
    user_ns=$1
fi

if [ ! $INSTRUMENT ]; then
    exclude_flag="-e"
    exclude_pattern="instrumented"
    ns_flag="-n"
    ns=""
fi

if [ ! $SKIP_CLJ ]; then
    echo "=== Running clojure test $1"
    clojure -R:test:test-clj \
            -e "(require,'patch.clj-2443)" \
            -m cognitect.test-runner -d src \
            "$ns_flag" "$ns" \
            -n "$user_ns" \
            "$exclude_flag" "$exclude_pattern"
fi

if [ $? -eq 1 ]; then
    exit_code=1
fi

if [ ! $SKIP_CLJS ]; then
    echo -e "\n=== Running cljs test $1"
    mkdir -p cljs-test-runner-out/gen
    clojure -A:test:test-cljs \
            -d src \
            "$ns_flag" "$ns" \
            -n "$user_ns" \
            "$exclude_flag" "$exclude_pattern" \
            -c cljs-opts.edn
fi

if [ $? -eq 1 ]; then
    exit_code=1
fi

exit $exit_code
