#!/bin/sh

exit_code=0
ns_flag="-n"
ns="aos.instrument"

if [ ! $INSTRUMENT ]; then
    exclude_flag="-e"
    exclude_pattern="instrumented"
    ns_flag="-n"
    ns=""
fi

echo "=== Running clojure test $1"
clojure -R:test:test-clj \
        -e "(require,'patch.clj-2443)" \
        -m cognitect.test-runner -d src \
        "$ns_flag" "$ns" \
        -n "$1" \
        "$exclude_flag" "$exclude_pattern"

if [ $? -eq 1 ]; then
    exit_code=1
fi

echo "\n=== Running cljs test $1"
mkdir -p cljs-test-runner-out/gen
clojure -A:test:test-cljs \
        -d src \
        "$ns_flag" "$ns" \
        -n "$1" \
        "$exclude_flag" "$exclude_pattern" \
        -c cljs-opts.edn

if [ $? -eq 1 ]; then
    exit_code=1
fi

exit $exit_code
