#!/bin/bash

exit_code=0

if [ ! $INSTRUMENT ]; then
    regex="aoc\.y.*\.d.*(?<!data)"
    exclude_flag="-e"
    exclude_pattern="instrumented"
else
    regex="aoc\.instrument|aoc\.y.*\.d.*(?<!data)"
fi

if [ ! $SKIP_CLJ ]; then
    echo "=== Running clojure tests $exclude"
    clojure -J-Xmx3200m \
            -R:test:test-clj \
            -O:test-clj \
            -e "(require,'patch.clj-2443)" \
            -m cognitect.test-runner -d src -r "$regex" \
            -e "slow" \
            "$exclude_flag" "$exclude_pattern"
fi

if [ ! $? ]; then
    exit_code=1
fi

if [ ! $SKIP_CLJS ]; then
    echo -e "\n=== Running cljs tests"
    mkdir -p cljs-test-runner-out/gen
    clojure -A:test:test-cljs \
            -d src -r "$regex" \
            -e "slow" \
            -e "skip-cljs" \
            "$exclude_flag" "$exclude_pattern" \
            -c cljs-opts.edn \
            -D doo-opts.edn
fi

if [ $? != 0 ]; then
    exit_code=1
fi

exit $exit_code
