#!/bin/bash

exit_code=0

files=$(git diff --name-only origin/master..HEAD)
namespaces=$(echo "$files" | grep '^src\|^test' \
                 | sed 's/^src\///' \
                 | sed 's/^test\///' \
                 | sed 's/\.cljc$//' \
                 | sed 's/\//\./g')

echo -e "The following namespaces are different from master and will be tested if present in this branch:\n$namespaces"

namespaces=$(echo "$namespaces" \
                 | tr '\r\n' '#' \
                 | echo "#$(cat -)" \
                 | sed 's/#$//' \
                 | sed 's/#/ -n /g')

clj_cmd="clojure -J-Xmx3200m -R:test:test-clj -e (require,'patch.clj-2443) -m cognitect.test-runner -d src $namespaces"

$clj_cmd

if [ $? -eq 1 ]; then
    exit_code=1
fi

mkdir -p cljs-test-runner-out/gen

cljs_cmd="clojure -A:test:test-cljs -d src -c cljs-opts.edn $namespaces"

$cljs_cmd

if [ $? -eq 1 ]; then
    exit_code=1
fi

exit $exit_code
